sudo: required
language: python
python:
  - "3.7"
os:
  - linux
git:
  depth: 3
branches:
  only:
  - /.*/
install:
  - sudo apt-get update
  - pip install pipenv
  - pipenv install .[DOCS, TESTS]
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3  # give xvfb some time to start
script:
  - pytest